name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: ["master", "CI"]
  pull_request:
    branches: ["master", "CI"]

env:
  BUILD_TYPE: Release
  CMAKE_BUILD_PARALLEL_LEVEL: 4

jobs:
  # ===============================================================
  Linux-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Downloads pd-Sources
        shell: bash
        run: |
          curl -L -o pure-data.zip https://api.github.com/repos/pure-data/pure-data/zipball/refs/tags/0.55-0
          unzip pure-data.zip
          rm pure-data.zip
          mv pure-data-* pure-data

      - name: Configure pd-else
        run: |
          cmake -BBuild -DPD_PATH=${{github.workspace}}/pure-data

      - name: Build pd-else
        run: |
          cmake --build Build

      - name: Upload Zip
        uses: actions/upload-artifact@v3
        with:
          name: else
          path: ./Build/else

  # ===============================================================
  macOS-Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Downloads pd sources
        shell: bash
        run: |
          curl -L -o pure-data.zip https://api.github.com/repos/pure-data/pure-data/zipball/refs/tags/0.55-0
          unzip pure-data.zip
          rm pure-data.zip
          mv pure-data-* pure-data

      - name: Configure pd-else
        run: |
          cmake -BBuild -DPD_PATH=${{github.workspace}}/pure-data

      - name: Build pd-else
        run: |
          cmake --build Build

      - name: Upload Zip
        uses: actions/upload-artifact@v3
        with:
          name: else
          path: ./Build/else

  # ===============================================================

  Windows-Build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - if: runner.os == 'Windows'
        name: "Install mingw deps"
        uses: msys2/setup-msys2@v2
        with:
          install: make mingw-w64-x86_64-gcc mingw64/mingw-w64-x86_64-cmake
          update: false

      - name: Get Pd
        shell: bash
        run: |
          curl -L -o pure-data.zip http://msp.ucsd.edu/Software/pd-0.55-0.msw.zip
          unzip pure-data.zip
          rm pure-data.zip
          mv pd-0.55-0 pd

      - name: Configure pd-else
        shell: msys2 {0}
        run: |
          cmake -G"MSYS Makefiles" -BBuild -DPD_PATH=./pd

      - name: Build pd-else
        shell: msys2 {0}
        run: |
          cmake --build Build
          rm -rf ./Build/else/*.a

      - name: Upload Zip
        uses: actions/upload-artifact@v3
        with:
          name: else
          path: ./Build/else
